# .github/workflows/branch-protection-trigger.yml
name: Branch Protection Rule Trigger

on:
  branch_protection_rule:
    types: [created, edited, deleted]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Log Branch Protection Event
        run: echo "A branch protection rule event has been triggered."
